version: '3'

networks:
  finance-manager-dev:

services:
  db:
    image: mariadb:10.5.4-focal
    container_name: finance-manager-dev-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - finance-manager-dev
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: finance-manager-elasticsearch-dev
    environment:
      - discovery.type=single-node
      - node.name=finance-manager-elasticsearch-dev
      - cluster.name=finance-manager
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - finance-manager-dev
  kibana:
    container_name: finance-manager-kibana-dev
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - finance-manager-dev